### PR TITLE
Add Selected Apps Label, Reshuffel the nesting of the checkbox and th…

### PR DESCRIPTION
**Pull request by Marterich**
Animation

(I cut a bit of the Waiting time for "Get Installed" so the GIF isn't that long and boring)
Note: Reason for the duplicate PR. I had to fix my branch name and didn't know how to keep the PR open.

### CODE REVIEW

**Comment by MyDrift-user** [comment]
Looks amazing thanks.
I had the Idea while watching that the list with selected applications could be a list like the options, meaning you could uncheck application through clicking on them in that list.

What do you think?

**Comment by Marterich** [comment]
Technically possible but harder because you have to manually define the drop-down again. We can keep that in mind, but I would focus on the general functionality first

**Comment by Marterich** [comment]
Changes from last Commit: 
- Allow selection / click on the whole section for an app
- Add visual representation for selection 
(Light Theme fixes will be done at the end, because i cannot bother to do serious theming at the moment)
Selection Indicator

**Comment by MyDrift-user** [comment]
So cool, thanks for your amazing help with this :)

**Comment by MyDrift-user** [comment]
what i noticed is that if you for example click on the name, checkbox or the logo it will be checked/unchecked but not highlighted/dehighlighted, maybe map the highlight/dehighlight depending on if it is checked or not.

image

**Comment by Marterich** [comment]
Will take a look at this later 
Edit: Fixed in https://github.com/MyDrift-user/winutil/pull/11/commits/14584cee63ed09d01ef8548e95f54e90c6be9691

**Comment by MyDrift-user** [comment]
Nice, could not find any other functional issue of the changes after this commit.

**Comment by Marterich** [comment]
The contents of this PR got merged already with another PR

**Pull request closed without merging**
